<?php


abstract class SecoesEnum
{
    //USUARIO SECOES
    const LOGIN = "LOGIN";
    const NOME = "NOME";
    const EMAIL = "EMAIL";
    const CPF = "CPF";
    const NIVEL_USUARIO = "NIVELUSUARIO";
    const FOTO_USUARIO = "FOTOUSUARIO";
    const IDUSUARIOCONTEXTO = "IDUSUARIOCONTEXTO";
    const IDFUNCIONARIOCONTEXTO = "IDFUNCIONARIOCONTEXTO";


    const CURRICULO = "CURRICULO";
    const NUMERO_TELEFONE = "NUMEROTELEFONE";
    const AVALIACAO_MEDIA = "AVALIACAOMEDIA";
    //FIM USUARIO SECOES
    const SERVICOS = "SERVICOS";

}
